%%--DRAW SLIDER
Screen('TextSize', mywindow, floor((30*scale_res(2))));
bid_msg = sprintf('Indicate to what extent you feel this way right now:');
[normBoundsRect, ~] = Screen('TextBounds', mywindow, bid_msg);
Screen('DrawText', mywindow, bid_msg, (centerhoriz-(normBoundsRect(3)/2)), (centervert-(normBoundsRect(4)/2)), black);
w = sprintf('%s',words{1});
[normBoundsRect, ~] = Screen('TextBounds', mywindow, w);
Screen('TextStyle', mywindow, 1);
Screen('DrawText', mywindow, w, (centerhoriz-(normBoundsRect(3)/2)), (centervert+30), black);
Screen('TextStyle', mywindow, 0);
CenterSpotHor = centerhoriz;
CenterSpotVert = centervert+190;
value = 0;
oval_rect = [CenterSpotHor-10 CenterSpotVert-10 CenterSpotHor+10 CenterSpotVert+10];
xRad_O = 10; % size of the oval (pixels)
yRad_O = xRad_O;
%Screen('TextSize', mywindow, 30);
Screen('TextFont', mywindow, 'Helvetica');
Screen('TextStyle', mywindow, 0);
Screen('TextSize', mywindow, 25);
value_msg = sprintf('%.2g ',value);
[normBoundsRect, ~] = Screen('TextBounds', mywindow, value_msg);
Screen('DrawText', mywindow, value_msg, (centerhoriz-(normBoundsRect(3)/2)), (centervert+(155)), black);
Screen('FillOval', mywindow, black, oval_rect );
draw_scale;
Screen('Flip', mywindow);
Screen('TextSize', mywindow, floor((30*scale_res(2))));
bid_msg = sprintf('Indicate to what extent you feel this way right now:');
[normBoundsRect, ~] = Screen('TextBounds', mywindow, bid_msg);
Screen('DrawText', mywindow, bid_msg, (centerhoriz-(normBoundsRect(3)/2)), (centervert-(normBoundsRect(4)/2)), black);
w = sprintf('%s',words{1});
[normBoundsRect, ~] = Screen('TextBounds', mywindow, w);
Screen('TextStyle', mywindow, 1);
Screen('DrawText', mywindow, w, (centerhoriz-(normBoundsRect(3)/2)), (centervert+30), black);
Screen('TextStyle', mywindow, 0);
fix_color = black;
text_color = black;
keep_going = 1;
